name: tensorflow-object-detection
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - lxml
    - scipy
    - ffmpeg
    - imageio==2.1.2
    - pip:
        - tensorflow-gpu==1.5.0
        - tensorflow-tensorboard==0.1.8
